### ISSUE TITLE
在新版的ANCC6.4中最后户相关的SAC文件的经纬度问题

### ISSUE THREAD

**Issue by qy02101** [YoushanLiu/ANCC#5]
你好刘老师，我在使用你的新版ANCC6.3时发现一个问题，就是最后的互相关计算结果的SAC文件，在SAC中经度坐标写成纬度坐标了，纬度坐标写成经度坐标了。我将run.py文件中的saclst knetwk kstnm stla stlo delta f %s | awk '{print $2,$3,$4,$5,$6}' >> stations.junk,修改为saclst knetwk kstnm stla stlo delta f %s | awk '{print $2,$3,$5,$4,$6}' >> stations.junk ，在互相关结果中经纬度就正确写入了。

**Comment by YoushanLiu** [comment]
谢谢你的反馈。我刚才看了一下代码，没有发现有啥问题。
![image](https://user-images.githubusercontent.com/19830127/228228524-71a13def-c208-461f-915c-3afed8091f66.png)
而且，你的修改也没有变化。从saclst knetwk kstnm stla stlo delta 改为saclst knetwk kstnm stla stlo delta 未看出任何变化。

**Comment by qy02101** [comment]
gawk  {print $2,$3,$5,$4,$6}'  我只是把gawk  中间部分的4 5字段交换了以下，今天是发现这个问题，回来重新运行了结果也是！交换了下，交换了下就好了！

**Comment by qy02101** [comment]
谢谢刘老师的解答！

**Comment by YoushanLiu** [comment]
谢谢你的反馈。我再次核对了读入station.lst的地方，的确读入的是网络名，台站名，经度，维度，高程等信息。
![image](https://user-images.githubusercontent.com/19830127/228230761-19a657b5-3520-4454-a090-925a88c1deb9.png)
原始的写法saclst knetwk kstnm stla stlo delta f %s | awk '{print $2,$3,$4,$5,$6}'和这个顺序对应，调换之后可能反倒不对了。在输出前会基于经度度计算台站距离并存到SAC道头里，如果经纬度不对，计算的距离也会出问题。我这边查看了我的输出，叠加前和叠加后的似乎经纬度和距离计算都是正确的。你看看是不是你的数据的道头写错了。如果你使用我的预处理的脚本的话，台站的stainfo.lst是顺序是网络名，台站名，纬度，经度，高程。你查看一下是否是你的stainfo.lst写反了。

**Comment by YoushanLiu** [comment]
看到了。的确，这个run.py和我自己使用的不太一样。我已经修改了run.py和主程序，现在已经匹配。谢谢你的反馈。

**Comment by qy02101** [comment]
谢谢刘老师



---原始邮件---
发件人: "Youshan ***@***.***&gt;
发送时间: 2023年3月28日(周二) 晚上8:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YoushanLiu/ANCC] 在新版的ANCC6.4中最后户相关的SAC文件的经纬度问题 (Issue #5)




 
看到了。的确，这个run.py和我自己使用的不太一样。我已经修改了run.py和主程序，现在已经匹配。谢谢你的反馈。
